# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Synplus | Dsw
email: stephaniecruzcastelli@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "templategenerator" # the subpath of your site, e.g. /blog
template1-url: "/1-corporate-template/"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  stephanie-cruz
#gems: [jekyll-paginate]
#paginate: 4
#paginate_path: "/blog/page:num/"
# Build settings

sass:
  load_paths:
        - _sass
        - 1-corporate-template/_sass

kramdown:
  input: GFM

#collections_dir: 1-corporate-template

collections:
  services:
    output: true
    permalink: templategenerator/1-corporate-template/:path.html
  blogs:
    output: true
    permalink: templategenerator/1-corporate-template/:path.html
 

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"    
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog" 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - propuesta
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
