# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl:  "templategenerator" #
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: synergyvision/templategenerator
#gems: [jekyll-paginate]
#paginate: 4
#paginate_path: "1-corporate-template/blogs/page:num/"
# Build settings

destination: docs

sass:
  load_paths:
        - _sass
        - 1-corporate-template/_sass
        - 2-online-courses-template/_sass
        - 3-culinary-blog-template/_sass
  style: compressed
  
kramdown:
  input: GFM

#collections_dir: 1-corporate-template

collections:
  corporate-services:
    output: true
    permalink: 1-corporate-template/services/:path.html
  corporate-blogs:
    output: true
    permalink: 1-corporate-template/blogs/:path.html
  online-courses-categories:
    output: true
    permalink: 2-online-courses-template/categories/:path.html
  online-courses-courses:
    output: true
    permalink: 2-online-courses-template/courses/:path.html
  online-courses-blog:
    output: true
    permalink: 2-online-courses-template/blog/:path.html
  online-courses-info:
    output: true
    permalink: 2-online-courses-template/info/:path.html
  culinary-blog-recipes:
    output: true
    permalink: 3-culinary-blog-template/recipes/:path.html
  culinary-blog-courses:
    output: true
    permalink: 3-culinary-blog-template/courses/:path.html
  culinary-blog-techniques:
    output: true
    permalink: 3-culinary-blog-template/techniques/:path.html
plugins:
#    - jekyll-minifier
#    - jekyll-paginate-v2




defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"    
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog" 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

exclude:
  - propuesta
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
