
cards-services:
  - card: Card1
    title: Title 1
    subtitle: Best subtitle ever
    category: Category 1
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
  - card: Card2
    title: Title 2
    subtitle: Best subtitle ever
    category: Category 2
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
  - card: Card3
    title: Title 3
    subtitle: Best subtitle ever
    category: Category 3
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
  - card: Card4
    title: Title 4
    subtitle: Best subtitle ever
    category: Category 4
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
  - card: Card5
    title: Title 5
    subtitle: Best subtitle ever
    category: Category 5
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
  - card: Card6
    title: Title 6
    subtitle: Best subtitle ever
    category: Category 6
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
  - card: Card7
    title: Title 7
    subtitle: Best subtitle ever
    category: Category 7
    button: Learn more &rarr;
    img: firsti.jpg
    description: New York, the largest city in the U.S., is an architectural marvel with plenty of historic monuments, magnificent buildings and countless dazzling skyscrapers.
